---

- name: Get `knife` status
  local_action: command type knife
  register: knife_status
  ignore_errors: True

- name: Check if `knife` is installed
  set_fact:
    knife_is_installed: "{{ not knife_status.stderr }}"

- local_action: command echo "Warning ==> Knife solo is not installed"
  when: not knife_is_installed

- name: Run knife solo prepare
  local_action: command knife solo prepare {{chef_user}}@{{chef_host}}
  args:
      chdir: "{{chef_dir}}"
  when: knife_is_installed and run_knife_solo_prepare
  register: chef_output
  ignore_errors: true

- debug: var=chef_output.stdout_lines

- name: Run knife solo cook
  local_action: command knife solo cook {{chef_user}}@{{chef_host}}
  args:
      chdir: "{{chef_dir}}"
  when: knife_is_installed and run_knife_solo_cook
  register: chef_output
  ignore_errors: true

- debug: var=chef_output.stdout_lines
...
