source "https://rubygems.org"

group :chef do
  gem "berkshelf", "~> 4.3"
  gem "chef", "~> 12.10.24"
  gem "knife-solo", "~> 0.6.0"
  gem "knife-solo_data_bag", "~> 1.1.0"
end

group :chef_development do
  gem "foodcritic", "~> 6.2"
  gem "chefspec", "~> 4.6"
  gem "test-kitchen", "~> 1.8.0"
  gem "kitchen-vagrant", "~> 0.20.0"
  gem "kitchen-docker", "~> 2.3.0"
  #gem "rubocop", "~> 0.40.0"
  gem "ohai", "~> 8.17.0"
end

group :deploy do
  gem "capistrano", "~> 2.15.5"
  gem "railsless-deploy", "~> 1.1"
  gem 'capifony', '~> 2.8.6'
  gem "compass", "~> 1.0.3"
end

group :test do
  # CI / testing
  gem 'serverspec', '~> 2.31'
end

# Execution helpers
if Bundler.settings[:path].nil?
  gem 'rubygems-bundler', '~> 1.4.4'
  gem 'executable-hooks', '~> 1.3.2'
end
